### ISSUE TITLE
define and describe debug.log(keys) format

### ISSUE THREAD

**Issue by nayuta-gondo** [nayutaco/lightning-dissector#2]

**Comment by nayuta-gondo** [comment]
ref. https://jimshaver.net/2015/02/11/decrypting-tls-browser-traffic-with-wireshark-the-easy-way/

**Comment by nayuta-gondo** [comment]
About the format of The key log file

ref.https://www.trustwave.com/Resources/SpiderLabs-Blog/How-To-Decrypt-Ruby-SSL-Communications-with-Wireshark/

>The general format is "<id> <key>". 

We should follow the following rough format guidelines.

id: First 18 bytes of encrypted packet ???
key: A sending key and a nonce ???

**Comment by tock203** [comment]
Done https://github.com/nayutaco/lightning-dissector/blob/master/CONTRIBUTING.md
