### ISSUE TITLE
[Eclair] Dissector can't parse keys

### ISSUE THREAD

**Issue by t-bast** [nayutaco/lightning-dissector#31]
Hey,

First of all thanks for doing this, it's going to be really helpful for newcomers such as myself.
I'm trying to use the dissector with 3 eclair nodes running locally.
I'm on Ubuntu 18.04, capturing with Wireshark on the loopback interface. I configured the logs location with the path to my 3 nodes (with the `:` separator as indicated in the tool).
I launched Wireshark before my Eclair nodes, made a few payments, but nothing appears when I filter for `lightning`.
How can I troubleshoot where the issue is coming from? Could it be a change in Eclair that doesn't dump the keys/nonces properly to the log file (I am in debug mode as instructed)?

Thanks!

**Comment by t-bast** [comment]
I gave this another try today and was able to make progress.

The first issue I had is that the dissector only looks at tcp packets on port 9735, whereas my local tests were using ports 48000, 48001 and 48002. I think it would be useful to let the user configure additional ports to monitor (in my case I simply updated the source code to include those ports as I'm a beginner in lua/wireshark plugins).

The second issue is more linked to Eclair. By reading the plugin code I was able to find the regex used to parse the `eclair.log` file, and I think this regex is quite brittle (and has probably been broken by a change in the eclair logging code). The regex looks for:

`encrypt\\(([0-9a-f]+), ([0-9a-f]+), .+ = .+`

But my log lines look like:

 `2019-04-30 14:09:12,238 DEBUG f.a.e.c.ChaCha20Poly1305$  - encrypt(ByteVector(32 bytes, 0x7579e5d144495d2bc2b30cde3cb689fe4687fe0ab052c6cec1e32709716b921a), ByteVector(12 bytes, 0x000000001a00000000000000), ByteVector(empty), ByteVector(2 bytes, 0x0063)) = (ByteVector(2 bytes, 0x2ba8), ByteVector(16 bytes, 0xa59f3ef68acf1fa9f21c7775542a5ec5))` 

I think the addition of the `ByteVector` information breaks the regex. I think it would be better to migrate eclair to dump keys to the key log just like c-lightning and lnd. I'll work on this when I have some time available.

**Comment by tock203** [comment]
Thanks for the information!

> I think it would be better to migrate eclair to dump keys to the key log just like c-lightning and lnd.

Yes it definitely is. We plan to remove eclair-specific code from lightning-dissector when eclair can write out the key log file

**Comment by t-bast** [comment]
Cool, I'll work on eclair to support the key log file.
I'll update this issue when it's ready.

**Comment by t-bast** [comment]
I have created a PR on eclair to emit the `keys.log` file (https://github.com/ACINQ/eclair/pull/981).
I also have the changes to the `lightning-dissector` locally that remove the eclair-specific code and use the standard keylogfactory (and a documentation update). I'll send you a PR once the eclair changes are merged.
