### ISSUE TITLE
Start using a version

### ISSUE THREAD

**Issue by pocc** [nayutaco/lightning-dissector#35]
If there is a version in this repo, I could not find it. Semver (semver.org) is usually used to create version numbers. You can then use these version numbers as github tags for [releases](https://help.github.com/en/articles/creating-releases). 

If this is not stable, it's fine to use a 0.x.y version.

**Comment by nayuta-gondo** [comment]
https://github.com/nayutaco/lightning-dissector/releases/tag/v0.1.0
