### ISSUE TITLE
create a preference

### ISSUE THREAD

**Issue by nayuta-gondo** [nayutaco/lightning-dissector#5]
- dst port number
- debug.log path

can be set in LN protocol preference.

**Comment by nayuta-gondo** [comment]
ref. https://jimshaver.net/wp-content/uploads/2015/02/2015-02-11-21_47_10-Wireshark_-Preferences-Profile_-Default.jpg

**Comment by tock203** [comment]
Done
![screenshot at 2018-09-17 18-18-38](https://user-images.githubusercontent.com/12756700/45614966-21404e00-baa6-11e8-9678-2a5b51f1f580.png)
